export const PRODUCT_CATEGORIES = [
  'Cyclisme',
  'Route',
  'VTT',
  'Gravel',
  'Triathlon',
  'Course a pied',
  'Trail',
  'Marche nordique',
  'Randonnee',
  'Escalade',
  'Camping',
  'Fitness',
  'Musculation',
  'CrossFit',
  'Yoga',
  'Pilates',
  'Tennis',
  'Padel',
  'Badminton',
  'Natation',
  'Sports d hiver',
  'Sports collectifs',
  'Sports de combat',
  'Electromobilite',
  'Accessoires',
] as const;

export const ALL_CATEGORIES_LABEL = 'Toutes les categories';
